# Generated by Django 6.0.5 on 2026-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsnippet',
            name='lang_code',
            field=models.CharField(default='deu', help_text="e.g. 'deu' or 'lat'", max_length=3, verbose_name='Language code'),
        ),
        migrations.AddField(
            model_name='textsnippet',
            name='vectorized',
            field=models.BooleanField(default=False, verbose_name='Embeddings exist'),
        ),
    ]
