# Generated by Django 6.0.5 on 2026-05-21 05:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0002_textsnippet_lang_code_textsnippet_vectorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="textsnippet",
            name="vector_column",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="textsnippet",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vector_column"], name="archiv_text_vector__6be340_gin"
            ),
        ),
    ]
