# Generated by Django 6.0.5 on 2026-05-28 08:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_create_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(help_text='Input/Question provided by the user', max_length=500, verbose_name='Question')),
                ('text_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Embedding (nomic-embed-text-v1.5)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
