# Generated by Django 6.0.5 on 2026-05-28 08:42

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_userinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User input', 'verbose_name_plural': 'User inputs'},
        ),
        migrations.AddIndex(
            model_name='userinput',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='userinput_nomic', opclasses=['vector_l2_ops']),
        ),
    ]
